# Generated by Django 5.1.15 on 2026-01-19 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('key', models.CharField(help_text="Unique key for the setting (e.g. 'show_prices')", max_length=50, unique=True)),
                ('value', models.JSONField(default=dict, help_text='JSON value for the setting')),
                ('description', models.CharField(blank=True, help_text='Human-readable description', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
