# Generated by Django 5.1.15 on 2026-01-11 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_stock_qty_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name_tr', models.CharField(help_text='Category name in Turkish', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='Category name in English', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether category is active')),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blog categories',
                'ordering': ['order', 'name_tr'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly slug', unique=True)),
            ],
            options={
                'verbose_name': 'blog tag',
                'verbose_name_plural': 'blog tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Short excerpt for previews (max 500 chars)', max_length=500)),
                ('content', models.TextField(help_text='Full post content (HTML or Markdown)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', help_text='Publication status', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Publication date/time', null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show in featured section')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('reading_time_min', models.PositiveSmallIntegerField(default=1, help_text='Estimated reading time in minutes')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160)),
                ('author', models.ForeignKey(blank=True, help_text='Post author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Post category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('cover_media', models.ForeignKey(blank=True, help_text='Cover image for the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_covers', to='catalog.media')),
                ('tags', models.ManyToManyField(blank=True, help_text='Post tags', related_name='posts', to='blog.blogtag')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_blogpo_status_c0e87f_idx'), models.Index(fields=['is_featured', '-published_at'], name='blog_blogpo_is_feat_1c3903_idx'), models.Index(fields=['category', '-published_at'], name='blog_blogpo_categor_dbd54f_idx')],
            },
        ),
    ]
