# Generated by Django 5.1.15 on 2026-01-10 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_media_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('kind', models.CharField(choices=[('variants_csv', 'Variants CSV'), ('products_csv', 'Products CSV'), ('taxonomy_csv', 'Taxonomy CSV')], db_index=True, help_text='Type of import job', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], db_index=True, default='pending', help_text='Current status of the import', max_length=16)),
                ('dry_run', models.BooleanField(default=True, help_text='If true, only validate without making changes')),
                ('allow_partial', models.BooleanField(default=False, help_text='If true, allow partial success (some rows may fail)')),
                ('report_json', models.JSONField(blank=True, default=dict, help_text='Validation/execution report with errors and counts')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the import job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('input_file', models.ForeignKey(blank=True, help_text='Uploaded CSV/Excel file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='catalog.media')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('actor_email', models.EmailField(blank=True, help_text='Email snapshot (in case user is deleted)', max_length=254)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('media_upload', 'Media Upload'), ('media_delete', 'Media Delete'), ('media_reorder', 'Media Reorder'), ('taxonomy_generate', 'Taxonomy Generate'), ('import_apply', 'Import Apply'), ('template_apply', 'Template Apply'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, help_text='Type of action performed', max_length=32)),
                ('entity_type', models.CharField(db_index=True, help_text="Model/entity type (e.g., 'product', 'variant')", max_length=64)),
                ('entity_id', models.CharField(db_index=True, help_text='Entity ID (UUID or primary key)', max_length=64)),
                ('entity_label', models.CharField(blank=True, help_text='Human-readable label (e.g., product title)', max_length=255)),
                ('before_json', models.JSONField(blank=True, default=dict, help_text='State before the change (only changed fields)')),
                ('after_json', models.JSONField(blank=True, default=dict, help_text='State after the change (only changed fields)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., import job ID, batch info)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Client user agent', max_length=512)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ops_auditlo_entity__52db88_idx'), models.Index(fields=['actor', 'created_at'], name='ops_auditlo_actor_i_4e40ac_idx'), models.Index(fields=['action', 'created_at'], name='ops_auditlo_action_f4d18a_idx')],
            },
        ),
    ]
