# Generated by Django 5.1.15 on 2026-01-29 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_seo_description_and_more'),
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='dry_run',
        ),
        migrations.AddField(
            model_name='importjob',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of input file for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='importjob',
            name='is_preview',
            field=models.BooleanField(default=True, help_text='If true, only validate without making changes (dry-run)'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='mode',
            field=models.CharField(choices=[('strict', 'Strict (fail on missing references)'), ('smart', 'Smart (create missing entities with approval)')], default='strict', help_text='Import mode for handling missing references', max_length=16),
        ),
        migrations.AddField(
            model_name='importjob',
            name='snapshot_file',
            field=models.ForeignKey(blank=True, help_text='Snapshot of normalized data (JSON/XLSX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_snapshots', to='catalog.media'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='snapshot_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of snapshot file', max_length=64),
        ),
        migrations.AddField(
            model_name='importjob',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='report_json',
            field=models.JSONField(blank=True, default=dict, help_text='Validation/execution report with errors, counts, and valid_rows'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['file_hash'], name='ops_ij_file_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', '-created_at'], name='ops_ij_status_created_idx'),
        ),
    ]
