# Generated by Django 5.1.15 on 2026-01-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem_snapshots_idempotency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_user_id_56cb86_idx',
            old_name='orders_cart_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_token_5c1a1c_idx',
            old_name='orders_cart_token_idx',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_status_7e2d77_idx',
            old_name='orders_cart_status_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_created_50584e_idx',
            old_name='orders_cart_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='orders_cart_cart_id_dc9f49_idx',
            old_name='orders_cartitem_cart_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='orders_cart_variant_339bb5_idx',
            old_name='orders_cartitem_variant_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='orders_cart_added_a_a6c368_idx',
            old_name='orders_cartitem_added_at_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='orders_idem_key_08c5cb_idx',
            old_name='orders_idem_key_scope_cart_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='orders_idem_created_6691b9_idx',
            old_name='orders_idem_created_idx',
        ),
    ]
