# Generated by Django 5.1.15 on 2026-01-10 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_model_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('title_tr', models.CharField(help_text='Turkish title', max_length=200)),
                ('title_en', models.CharField(blank=True, help_text='English title', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/main catalog')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order')),
                ('published', models.BooleanField(db_index=True, default=True, help_text='Visible on public site')),
            ],
            options={
                'verbose_name': 'catalog asset',
                'verbose_name_plural': 'catalog assets',
                'ordering': ['order', 'title_tr'],
            },
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['product', 'model_code'], 'verbose_name': 'variant', 'verbose_name_plural': 'variants'},
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_order_b0952e_idx',
            old_name='catalog_cat_order_2a1c5b_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_is_feat_bda135_idx',
            old_name='catalog_cat_is_feat_3c9d7e_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='catalog_cat_parent__1fff81_idx',
            old_name='catalog_cat_parent__8f4e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='media',
            new_name='catalog_med_kind_3777d4_idx',
            old_name='catalog_med_kind_5e8e3b_idx',
        ),
        migrations.RenameIndex(
            model_name='media',
            new_name='catalog_med_checksu_8f78b0_idx',
            old_name='catalog_med_checksu_8d9f9e_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_status_521020_idx',
            old_name='catalog_pro_status_7e4a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_is_feat_94b8d5_idx',
            old_name='catalog_pro_is_feat_8c3d5f_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_series__27488d_idx',
            old_name='catalog_pro_series__9f2e6a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_created_92b554_idx',
            old_name='catalog_pro_created_asc_idx',
        ),
        migrations.RenameIndex(
            model_name='productmedia',
            new_name='catalog_pro_sort_or_bb0f83_idx',
            old_name='catalog_pro_sort_or_7c8d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='productmedia',
            new_name='catalog_pro_product_7a4b52_idx',
            old_name='catalog_pro_product_9e5f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='series',
            new_name='catalog_ser_order_9d7373_idx',
            old_name='catalog_ser_order_7b3c1d_idx',
        ),
        migrations.RenameIndex(
            model_name='series',
            new_name='catalog_ser_is_feat_1fc2e5_idx',
            old_name='catalog_ser_is_feat_9e2f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='series',
            new_name='catalog_ser_categor_6ca9bb_idx',
            old_name='catalog_ser_categor_5d8e3c_idx',
        ),
        migrations.RenameIndex(
            model_name='taxonomynode',
            new_name='catalog_tax_order_cfcb7a_idx',
            old_name='catalog_tax_order_4c7d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='taxonomynode',
            new_name='catalog_tax_series__e9a21e_idx',
            old_name='catalog_tax_series__8a5f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='taxonomynode',
            new_name='catalog_tax_parent__ab628b_idx',
            old_name='catalog_tax_parent__2b6e9d_idx',
        ),
        migrations.RenameIndex(
            model_name='variant',
            new_name='catalog_var_product_5106de_idx',
            old_name='catalog_var_product_5e9a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='variant',
            new_name='catalog_var_sku_93f218_idx',
            old_name='catalog_var_sku_8f4b2d_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Internal product name', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf_ref',
            field=models.CharField(blank=True, help_text="PDF catalog reference (e.g., 'p9')", max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(help_text='Primary series for this product group', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.series'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_specs',
            field=models.JSONField(blank=True, default=list, help_text='3-5 bullet specs for product cards (legacy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, help_text='English title for catalog display', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_tr',
            field=models.CharField(help_text='Turkish title for catalog display', max_length=200),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(blank=True, help_text='Color variant (legacy)', max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='dimensions',
            field=models.CharField(blank=True, help_text="Dimensions (e.g., '400x630x280')", max_length=64),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name_en',
            field=models.CharField(blank=True, help_text='English model name', max_length=200),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name_tr',
            field=models.CharField(help_text='Turkish model name', max_length=200),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(help_text='Parent product group', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(blank=True, help_text='Size variant (legacy)', max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit (legacy)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['model_code'], name='catalog_var_model_c_2b438c_idx'),
        ),
        migrations.AddField(
            model_name='catalogasset',
            name='media',
            field=models.ForeignKey(help_text='PDF file (must be kind=pdf)', limit_choices_to={'kind': 'pdf'}, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_assets', to='catalog.media'),
        ),
        migrations.AddIndex(
            model_name='catalogasset',
            index=models.Index(fields=['order'], name='catalog_cat_order_1252ca_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogasset',
            index=models.Index(fields=['published'], name='catalog_cat_publish_ead547_idx'),
        ),
    ]
