# Generated by Django 5.1.15 on 2026-01-10 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_catalogasset_alter_variant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text="Template name (e.g., 'Gazlı Ocak Şablonu')", max_length=200, unique=True)),
                ('spec_layout', models.JSONField(blank=True, default=list, help_text='Ordered list of SpecKey slugs for table display')),
                ('default_general_features', models.JSONField(blank=True, default=list, help_text='Default general features to apply (if product has none)')),
                ('default_notes', models.JSONField(blank=True, default=list, help_text='Default notes to apply (if product has none)')),
                ('applies_to_parent_taxonomy_slug', models.CharField(blank=True, help_text='Optional: limit to products under this taxonomy node slug', max_length=160)),
                ('applies_to_series', models.ForeignKey(blank=True, help_text='Optional: limit this template to a specific series', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_templates', to='catalog.series')),
            ],
            options={
                'verbose_name': 'spec template',
                'verbose_name_plural': 'spec templates',
                'ordering': ['name'],
            },
        ),
    ]
