# Generated by Django 5.1.15 on 2026-01-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_spectemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('video', 'Video'), ('file', 'File')], db_index=True, default='image', help_text='Type of media file', max_length=10),
        ),
    ]
