# Generated by Django 5.1.15 on 2026-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_trigram_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='stock_qty',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Current stock quantity. NULL = unlimited stock, 0 = out of stock', null=True),
        ),
    ]
