# Generated by Django 5.1.15 on 2026-01-12 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_stock_qty_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('name', models.CharField(help_text='Brand name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brand description')),
                ('website_url', models.URLField(blank=True, help_text='Brand website URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether brand is active')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order (lower = first)')),
                ('logo_media', models.ForeignKey(blank=True, help_text='Brand logo image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_logos', to='catalog.media')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Product brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['order'], name='catalog_bra_order_cf38bf_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='catalog_bra_is_acti_0ff477_idx'),
        ),
    ]
