# Generated by Django 5.1.15 on 2026-01-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_series_explicit_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this brand-category combination is active')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order of brand within this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'brand category',
                'verbose_name_plural': 'brand categories',
                'ordering': ['category', 'order', 'brand__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='variant',
            name='variant_model_code_not_empty',
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(help_text='Primary series for this product group', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.series'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=160),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(help_text='Parent product group', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_series_slug_per_category'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='brand',
            field=models.ForeignKey(help_text='Brand in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='brand_categories', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='category',
            field=models.ForeignKey(help_text='Category in this relationship', on_delete=django.db.models.deletion.CASCADE, related_name='category_brands', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this brand operates in', related_name='brands', through='catalog.BrandCategory', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='brandcategory',
            index=models.Index(fields=['brand', 'category'], name='catalog_bra_brand_i_3cea13_idx'),
        ),
        migrations.AddIndex(
            model_name='brandcategory',
            index=models.Index(fields=['category', 'is_active', 'order'], name='catalog_bra_categor_f4b765_idx'),
        ),
        migrations.AddConstraint(
            model_name='brandcategory',
            constraint=models.UniqueConstraint(fields=('brand', 'category'), name='unique_brand_category'),
        ),
    ]
