# Generated by Django 5.1.15 on 2026-01-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_brand_category_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='series_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required', 'Required')], db_index=True, default='optional', help_text='Controls series requirement for products: disabled (no series), optional (default), required', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Product series (optional depending on category series_mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.series'),
        ),
    ]
