# Generated by Django 5.1.15 on 2026-01-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_category_series_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category (if series is not assigned)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Product subcategory (must be child of category)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_subcategory_products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='series_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required', 'Required')], db_index=True, default='disabled', help_text='Controls series requirement for products: disabled (no series), optional (default), required', max_length=10),
        ),
    ]
