# Generated by Django 5.1.15 on 2026-01-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_variant_model_code_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category (denormalized from Series)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.ForeignKey(help_text='Primary series for this product group', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.series'),
        ),
    ]
