# Generated by Django 5.1.15 on 2026-01-21 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_product_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLogoGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional title displayed when logo is clicked (defaults to brand name)', max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order of logo within category (lower = first)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this logo group is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Brand whose logo is displayed', on_delete=django.db.models.deletion.CASCADE, related_name='category_logo_groups', to='catalog.brand')),
                ('category', models.ForeignKey(help_text='Category this logo group belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logo_groups', to='catalog.category')),
            ],
            options={
                'verbose_name': 'category logo group',
                'verbose_name_plural': 'category logo groups',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LogoGroupSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the logo group')),
                ('is_heading', models.BooleanField(default=False, help_text='If true, this series is displayed as a heading (bold/prominent)')),
                ('logo_group', models.ForeignKey(help_text='Logo group this series belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logo_group_series', to='catalog.categorylogogroup')),
                ('series', models.ForeignKey(help_text='Series in this logo group', on_delete=django.db.models.deletion.CASCADE, related_name='logo_group_memberships', to='catalog.series')),
            ],
            options={
                'verbose_name': 'logo group series',
                'verbose_name_plural': 'logo group series',
                'ordering': ['logo_group', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='categorylogogroup',
            index=models.Index(fields=['category', 'order'], name='catalog_cat_categor_4c7704_idx'),
        ),
        migrations.AddIndex(
            model_name='categorylogogroup',
            index=models.Index(fields=['category', 'is_active'], name='catalog_cat_categor_5d8e0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='categorylogogroup',
            constraint=models.UniqueConstraint(fields=('category', 'brand'), name='unique_category_brand_logo_group'),
        ),
        migrations.AddConstraint(
            model_name='logogroupseries',
            constraint=models.UniqueConstraint(fields=('logo_group', 'series'), name='unique_logo_group_series'),
        ),
    ]
