# Generated by Django 5.1.15 on 2026-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_add_category_logo_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, help_text='SEO meta description', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title', max_length=255),
        ),
    ]
