# Generated by Django 5.1.15 on 2026-01-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Specific variant this image represents (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_media', to='catalog.variant'),
        ),
    ]
