# Generated by Django 5.1.15 on 2026-02-12 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_productmedia_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('title_tr', models.CharField(help_text='Turkish title', max_length=200)),
                ('title_en', models.CharField(blank=True, help_text='English title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Display order')),
                ('published', models.BooleanField(db_index=True, default=True, help_text='Visible on public site')),
                ('category', models.ForeignKey(help_text='Category this catalog belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='category_catalogs', to='catalog.category')),
                ('media', models.ForeignKey(help_text='PDF file (must be kind=pdf)', limit_choices_to={'kind': 'pdf'}, on_delete=django.db.models.deletion.PROTECT, related_name='category_catalog_files', to='catalog.media')),
            ],
            options={
                'verbose_name': 'category catalog',
                'verbose_name_plural': 'category catalogs',
                'ordering': ['order', 'title_tr'],
                'indexes': [models.Index(fields=['order'], name='catalog_cat_order_1212c7_idx'), models.Index(fields=['published'], name='catalog_cat_publish_f099de_idx')],
            },
        ),
    ]
