# Generated by Django 5.1.15 on 2026-02-16 14:01

import apps.catalog.models_qr
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_categorycatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('title', models.CharField(help_text="Belge başlığı (örn: 'GT-600 Serisi Ürün Bilgi Formu')", max_length=200)),
                ('pdf_file', models.FileField(help_text='PDF formatında ürün bilgilendirme formu', upload_to=apps.catalog.models_qr.info_sheet_pdf_path)),
                ('qr_code', models.ImageField(blank=True, help_text='Otomatik üretilen QR kod (PNG)', null=True, upload_to=apps.catalog.models_qr.info_sheet_qr_path)),
            ],
            options={
                'verbose_name': 'ürün bilgi formu',
                'verbose_name_plural': 'ürün bilgi formları',
                'ordering': ['-created_at'],
            },
        ),
    ]
