# Generated by Django 5.1.15 on 2026-03-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_product_info_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shadow_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for card shadow (e.g. #FF6B35). Empty = no colored shadow.', max_length=7),
        ),
    ]
