# Generated by Django 5.1.15 on 2026-03-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_add_category_shadow_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycatalog',
            name='media',
            field=models.ForeignKey(help_text='PDF file (accepts kind=pdf or kind=document)', limit_choices_to={'kind__in': ['pdf', 'document']}, on_delete=django.db.models.deletion.PROTECT, related_name='category_catalog_files', to='catalog.media'),
        ),
        migrations.AddConstraint(
            model_name='categorycatalog',
            constraint=models.UniqueConstraint(fields=('category', 'media'), name='unique_category_media'),
        ),
    ]
