# Generated by Django 5.1.15 on 2026-01-10 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_catalogasset_alter_variant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('full_name', models.CharField(help_text='Full name of the inquirer', max_length=200)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=30)),
                ('company', models.CharField(blank=True, help_text='Company name', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Inquiry message')),
                ('product_slug_snapshot', models.CharField(blank=True, help_text='Product slug at time of inquiry', max_length=255)),
                ('model_code_snapshot', models.CharField(blank=True, help_text='Model code at time of inquiry', max_length=32)),
                ('source_url', models.URLField(blank=True, help_text='URL where the inquiry was submitted from')),
                ('utm_source', models.CharField(blank=True, help_text='UTM source parameter', max_length=100)),
                ('utm_medium', models.CharField(blank=True, help_text='UTM medium parameter', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='new', help_text='Inquiry status', max_length=20)),
                ('internal_note', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
                ('product', models.ForeignKey(blank=True, help_text='Related product (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Related variant (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.variant')),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inquiries_i_status_8fae14_idx'), models.Index(fields=['-created_at'], name='inquiries_i_created_2b1632_idx'), models.Index(fields=['email'], name='inquiries_i_email_415ef2_idx')],
            },
        ),
    ]
