# Generated by Django 5.1.15 on 2026-01-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_spectemplate'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, help_text='Quantity requested')),
                ('product_slug_snapshot', models.CharField(blank=True, help_text='Product slug at time of inquiry', max_length=255)),
                ('product_title_tr_snapshot', models.CharField(blank=True, help_text='Product Turkish title at time of inquiry', max_length=200)),
                ('series_slug_snapshot', models.CharField(blank=True, help_text='Series slug at time of inquiry', max_length=160)),
                ('model_code_snapshot', models.CharField(blank=True, help_text='Model code at time of inquiry', max_length=32)),
                ('model_name_tr_snapshot', models.CharField(blank=True, help_text='Model Turkish name at time of inquiry', max_length=200)),
                ('inquiry', models.ForeignKey(help_text='Parent inquiry', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inquiries.inquiry')),
                ('variant', models.ForeignKey(blank=True, help_text='Related variant (if exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_items', to='catalog.variant')),
            ],
            options={
                'verbose_name': 'inquiry item',
                'verbose_name_plural': 'inquiry items',
                'ordering': ['id'],
            },
        ),
    ]
